### ISSUE TITLE
Create `Setup` Classes to allow configuration without writing real HOCON

### ISSUE THREAD

**Issue by to11mtm** [akkadotnet/Akka.Persistence.Sql#18]
With other parts of Akka.Net having `ActorSystemSetup` and similar, it would be nice to have the same capabilities here so that users can easily set up plugin configurations without having to write a bunch of HOCON.

This class should allow for configuration of all the 'important bits' that are exposed in HOCON configs.

 - It may be nice to provide a sort of 'forwarding' for providername with our own type/enum so users don't have to poke at `Linq2Db.ProviderName`
 - Validation/warning on invalid configs would also be a good idea (fail fast)

**Comment by Aaronontheweb** [comment]
@to11mtm after some of the work we were doing on Akka.Persistence.Redis earlier this week, I was considering proposing this for Akka.Persistence in general - having a `PersistenceSetup` that can be subclassed and used to provide implementation-specific configuration.

The use case I really like this for - being able to pass in connection strings programmatically.

**Comment by Aaronontheweb** [comment]
Akka.Peristence.Sql.Hosting solves this issue.

**Comment by Aaronontheweb** [comment]
Eh, guess not - we need this for stuff like pass-through identity, akin to what we do for Akka.Persistence.SqlServer
